name: Deploy Website
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v6
      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: dep-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Lint Code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    outputs:
      test-report: ${{ steps.test-file-name.outputs.report-file-name}}
    steps:
      - name: Get Code
        uses: actions/checkout@v6
      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: dep-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Run Test
        id: unit-test
        run: npm run test
      - name: Upload Test Report
        id: upload-test-report
        if: ${{ failure() && steps.unit-test.outcome == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: |
            test.json
      - name: Publish Report File Name
        if: ${{steps.upload-test-report.outcome != 'failure'}}
        id: test-file-name
        run: |
          find ./*.json -type f -execdir echo "report-file-name={}" >> $GITHUB_OUTPUT ';'
          echo "${{steps.upload-test-report.outputs.artifact-id}}"
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v6
      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: dep-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Build Website
        run: npm run build
  report:
    if: ${{failure()}}
    needs: [lint, test, deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Download Test Report
        uses: actions/download-artifact@v4
        with:
          name: test-report
      - name: Output Report
        run: |
          echo "${{ needs.test.outputs.test-report }}"
          cat "${{ needs.test.outputs.test-report }}"

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Website
        run: echo "Deploying ..."
