name: Reusable workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        type: string
        default: test-report
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: Deploy
        run: echo "Deploying ..."
