name: Reusable workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        type: string
        default: test-report
    secrets:
      admin-password:
        description: The password of the root admin (super-admin)
        required: true
    outputs:
      result:
        description: The result of the deployment operation
        value: ${{ jobs.deploy.outputs.outcome }}

jobs:
  deploy:
    outputs:
      outcome: ${{steps.result.outputs.step-result-success}}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: Deploy
        run: echo "Deploying ..."
      - name: Set Result Output
        id: result
        run: echo "step-result=success" >> $GITHUB_OUTPUT ';'
